// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// IKafkaWriter is an autogenerated mock type for the IKafkaWriter type
type IKafkaWriter struct {
	mock.Mock
}

// WriteMessages provides a mock function with given fields: ctx, logEvent, partitionNumber
func (_m *IKafkaWriter) WriteMessages(ctx context.Context, logEvent []byte, partitionNumber int) error {
	ret := _m.Called(ctx, logEvent, partitionNumber)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte, int) error); ok {
		r0 = rf(ctx, logEvent, partitionNumber)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewIKafkaWriter interface {
	mock.TestingT
	Cleanup(func())
}

// NewIKafkaWriter creates a new instance of IKafkaWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIKafkaWriter(t mockConstructorTestingTNewIKafkaWriter) *IKafkaWriter {
	mock := &IKafkaWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
