// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// StatusCmd is an autogenerated mock type for the StatusCmd type
type StatusCmd struct {
	mock.Mock
}

// Err provides a mock function with given fields:
func (_m *StatusCmd) Err() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewStatusCmd interface {
	mock.TestingT
	Cleanup(func())
}

// NewStatusCmd creates a new instance of StatusCmd. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewStatusCmd(t mockConstructorTestingTNewStatusCmd) *StatusCmd {
	mock := &StatusCmd{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
